# Generated by Django 4.2 on 2025-10-16 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_order_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('from_start', models.DateTimeField()),
                ('from_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
