# Generated by Django 4.2 on 2025-10-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupan_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupan',
            old_name='from_start',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='coupan',
            old_name='from_to',
            new_name='valid_to',
        ),
    ]
