# Generated by Django 4.2 on 2025-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_from_start_coupan_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupan',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
