# Generated by Django 4.2 on 2025-10-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_subcategory_category_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_subcategory',
            new_name='is_child_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='parent',
        ),
    ]
