# Generated by Django 4.2 on 2025-10-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_is_subcategory_category_is_child_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
