# Generated by Django 4.2 on 2025-10-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_parent_category_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_child_category',
            new_name='is_sub_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='sub_category',
        ),
    ]
